name: Build and Deploy

on:
  push:
    branches: [ "main" ]

jobs:
  build-and-deploy:
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build Docker image
        run: |
          cd ${{ github.workspace }}/webapp
          sudo docker build -t webapp:latest .

      - name: Deploy with Docker Compose
        run: |
          cd ${{ github.workspace }}
          sudo VAULT_TOKEN="${{ secrets.VAULT_TOKEN }}" docker compose up -d --build
